# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'haberApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'AEXML'
 pod 'Alamofire', '~> 5.0.0-rc.2'
 pod 'SDWebImage', '~> 5.0'

  # Pods for haberApp

end
